"""initial_schema

Revision ID: f9f246f7623b
Revises: 
Create Date: 2026-06-02 14:18:49.007076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9f246f7623b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('campaign_context', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('persona_id', sa.String(length=20), nullable=False),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_outlier', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id')
    )
    op.create_table('simulations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ad_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('persona_count', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('results_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sync_profiles',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='사용자 FK'),
    sa.Column('target_job', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='목표 직무'),
    sa.Column('interest_keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False, comment='관심 키워드 배열'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='갱신 시각'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_sync_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_sync_profiles_pkey')),
    comment='사용자 명시적 관심사/목표 직무'
    )
    op.create_table('raw_market_timeseries',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='yfinance 심볼'),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False, comment='거래일'),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='YAHOO_ETF_AI 등'),
    sa.Column('asset_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('theme', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'KRW'::character varying"), autoincrement=False, nullable=False),
    sa.Column('open_price', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True),
    sa.Column('high_price', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True),
    sa.Column('low_price', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True),
    sa.Column('close_price', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('turnover_amount', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('collected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('raw_market_timeseries_pkey')),
    sa.UniqueConstraint('ticker', 'trade_date', name=op.f('uq_raw_market_timeseries_ticker_date'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Bronze — 일별 OHLCV·거래대금 시계열'
    )
    op.create_index(op.f('ix_raw_market_ts_trade_date'), 'raw_market_timeseries', ['trade_date'], unique=False)
    op.create_index(op.f('ix_raw_market_ts_ticker_date'), 'raw_market_timeseries', ['ticker', 'trade_date'], unique=False)
    op.create_index(op.f('ix_raw_market_ts_source_type'), 'raw_market_timeseries', ['source_type'], unique=False)
    op.create_table('raw_opportunity_data',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='JOB / BOOTCAMP / CONTEST / SMES_* 등'),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=False, comment='원본 공고 링크'),
    sa.Column('raw_title', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='공고 제목'),
    sa.Column('host_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True, comment='주최/주관 기관 또는 기업명'),
    sa.Column('raw_content', sa.TEXT(), autoincrement=False, nullable=True, comment='원문 본문 (HTML/CDATA 원형 보존)'),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='지원 자격·상금 규모·근무지·경력 요건 등 부가정보'),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='공고 게시일 (등록일 우선)'),
    sa.Column('deadline_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='지원 마감일시 (앱 알림용)'),
    sa.Column('collected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='수집 시각'),
    sa.PrimaryKeyConstraint('id', name=op.f('raw_opportunity_data_pkey')),
    sa.UniqueConstraint('source_url', name=op.f('uq_raw_opportunity_data_source_url'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Bronze — 기회(채용·지원사업·부트캠프·공모전) 원천'
    )
    op.create_index(op.f('ix_raw_opportunity_source_type'), 'raw_opportunity_data', ['source_type'], unique=False)
    op.create_index(op.f('ix_raw_opportunity_deadline_at'), 'raw_opportunity_data', ['deadline_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False, comment='사용자 고유 식별자(UUID)'),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='로그인 이메일'),
    sa.Column('nickname', sa.VARCHAR(length=80), autoincrement=False, nullable=False, comment='서비스 표시 닉네임'),
    sa.Column('auth_provider', sa.VARCHAR(length=20), server_default=sa.text("'LOCAL'::character varying"), autoincrement=False, nullable=False, comment='LOCAL / GOOGLE / KAKAO / NAVER'),
    sa.Column('provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='OAuth 제공자 내부 사용자 ID'),
    sa.Column('profile_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='프로필 이미지 URL'),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='활성/휴면 상태'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='생성 시각'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='수정 시각'),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='사용자 기준 테이블'
    )
    op.create_index(op.f('idx_users_oauth'), 'users', ['auth_provider', 'provider_id'], unique=False)
    op.create_table('raw_economic_data',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='DART_API, VC_NEWS 등'),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True, comment='원문/출처 URL'),
    sa.Column('target_company_or_fund', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='투자 대상 기업·펀드'),
    sa.Column('investment_amount', sa.BIGINT(), autoincrement=False, nullable=True, comment='투자·유입 금액(원)'),
    sa.Column('collected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='수집 시각'),
    sa.Column('raw_title', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='공시 제목, 뉴스 헤드라인'),
    sa.Column('investor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='투자 주체'),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'KRW'::character varying"), autoincrement=False, nullable=False, comment='통화'),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='원천 데이터 확장 정보'),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='실제 공시일/기사 발행일'),
    sa.PrimaryKeyConstraint('id', name=op.f('raw_economic_data_pkey')),
    sa.UniqueConstraint('source_url', name=op.f('uq_raw_economic_data_source_url'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Bronze — 경제·투자·예산 등 자본 흐름 원천'
    )
    op.drop_table('simulations')
    op.drop_table('reports')
    op.drop_table('persona_responses')
    op.drop_table('ads')
    # ### end Alembic commands ###
